// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAjD-C_X9fcvUfvVqRl1mcDj2LWz5up8E',
    appId: '1:247873724493:web:5ba137f6c7d5a7e71d3c04',
    messagingSenderId: '247873724493',
    projectId: 'attendance-app-17762',
    authDomain: 'attendance-app-17762.firebaseapp.com',
    storageBucket: 'attendance-app-17762.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs4HOz3-cB3gEnci5Ow5eVyDg2-VKJdyU',
    appId: '1:247873724493:android:e5385e566b4550651d3c04',
    messagingSenderId: '247873724493',
    projectId: 'attendance-app-17762',
    storageBucket: 'attendance-app-17762.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0WvOuN6O6IdpbbEpzFX2NB01iy07a-Gw',
    appId: '1:247873724493:ios:2b5d5f26e7fbdf511d3c04',
    messagingSenderId: '247873724493',
    projectId: 'attendance-app-17762',
    storageBucket: 'attendance-app-17762.appspot.com',
    iosBundleId: 'com.example.aamecCseAttendanceApp',
  );
}
